### ISSUE TITLE
Sprites.css references githubusercontent.com

### ISSUE THREAD

**Issue by ajmas** [EducationLink/vue-tel-input#31]
Looking at sprites.css, I see the flag images are loaded from githubusercontent.com. This is a potential issue.

There should be a way for referencing these image files locally or at least provided a method to specify an alternative base path for these images.

Code in question:

```css
.iti-flag {
  width: 20px;
  height: 15px;
  box-shadow: 0px 0px 1px 0px #888;
  background-image: url("https://raw.githubusercontent.com/EducationLink/vue-tel-input/master/src/assets/flags.png");
  background-repeat: no-repeat;
  background-color: #dbdbdb;
  background-position: 20px 0;
}
@media only screen and (-webkit-min-device-pixel-ratio: 2), only screen and (min--moz-device-pixel-ratio: 2), only screen and (-o-min-device-pixel-ratio: 2), only screen and (min-device-pixel-ratio: 2), only screen and (min-resolution: 192dpi), only screen and (min-resolution: 2dppx) {
  .iti-flag {
    background-image: url("https://raw.githubusercontent.com/EducationLink/vue-tel-input/master/src/assets/flags@2x.png");
  }
}
```
